### ISSUE TITLE
Can't multiply with FixedTD: ValueError

### ISSUE THREAD

**Issue by jakobsarthur** [brightway-lca/bw_temporalis#36]
<img width="1453" alt="Screenshot 2023-10-12 at 09 55 17" src="https://github.com/brightway-lca/bw_temporalis/assets/22193631/c9c987d8-a183-4502-8de2-d0da41b708cf">

**Comment by jakobsarthur** [comment]
Ok, this bug is apparently not only an issue with FixedTD, also occurs when using just a normal TemporalDistribution with datetime array instead of timedelta.

**Comment by cmutel** [comment]
This issue was fixed in 9bb92ac501c6c6ec5e4e6c7b3a4ced3da66636a8. We can open a new one if necessary.
